export const USER_NOT_FOUND_STATUS = 404;

export const SERVER_ERROR_STATUS = 500;

export const USER_UUID_HEADER_NOT_FOUND_STATUS = 400;

export const BODY_PARAMETR_NOT_FOUND_STATUS = 400;

export const SUCCESS_GET_STATUS = 200;

export const SUCCESS_POST_WITH_CONTENT_STATUS = 200;
export const SUCCESS_POST_WITH_OUT_CONTENT_STATUS = 204;

export const SUCCESS_PUT_STATUS = 204;

export const SUCCESS_DELETE_STATUS = 204;
