export const ITEM_NOT_FOUND_STATUS = 404

export const SERVER_ERROR_STATUS = 500

export const PARAMETER_NOT_FOUND_STATUS = 400

export const SUCCESS_STATUS = 200

export const ITEM_IS_EXISTS_STATUS = 403
